version: "3"

services:
  streamer:
    build: 
        context: ./streamer/
        dockerfile: dockerfile
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./streamer/app/:/app/"
    networks:
      - fastapi

  capture:
    build: 
      context: ./capture/
      dockerfile: dockerfile
    volumes: 
      - "~/Videos/:/mnt/"
      - "./capture/app/:/app/"
    command: --source /mnt/test.mp4 --destination 10.10.10.2:8080
    depends_on:
      - streamer
    networks:
      - fastapi

networks:
  fastapi:
    name: fastapi
    external: true